version: "3.9"

services:
  frontend:
    container_name: compose-tools-frontend-container
    build:
      dockerfile: Dockerfile
    image: cr.yandex/crpfap56bqr8nkph7d9g/entools-tools-frontend
    platform: linux/amd64
    networks:
      - internet
    ports:
      - 8081:80
    restart: unless-stopped

networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
