# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]

env:
  # NODE_ENV: production
  # PORT: 4000
  IMAGE_NAME: cr.yandex/${{ secrets.CR_REGISTRY }}/${{ secrets.CR_REPOSITORY }}-tools-frontend:latest
  # HOST: ${{ secrets.HOST }}
  # API_HOST: ${{ secrets.API_HOST }}
  # YA_ENDPOINT: ${{ secrets.YA_ENDPOINT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: set_up_env
    steps:

      # initialize repo
      - uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
          CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          # NODE_ENV: ${{ env.NODE_ENV }}
          # PORT: ${{ env.PORT }}
          # API_HOST: ${{ secrets.API_HOST }}
          # YA_ENDPOINT: ${{ secrets.YA_ENDPOINT }}

        run: |
          echo CR_REGISTRY=${{ secrets.CR_REGISTRY }} >> .env.production
          docker compose build
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY-tools-frontend:latest

  update-yc:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy COI VM
      id: deploy-coi
      uses: yc-actions/yc-coi-deploy@v1.0.1
      env:
        YC_VM_SSH: ${{ secrets.YC_VM_SSH }}
        YC_VM_USERNAME: ${{ secrets.YC_VM_USERNAME }}
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        VM-name: ${{ secrets.YC_VM_NAME }}
        vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
        vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}

        docker-compose-path: './tools.dev/docker-compose.yaml'
        user-data-path: './tools.dev/user-data.yaml'
